### ISSUE TITLE
error Command failed with signal "SIGTERM".

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/frontend#32]
## ------備考--------

ビルドし直してのテストはしていないです(wifiないので。)
wifi環境にてもう一度試して見ます

### Step 1: 環境

 * OS: Darwin crystalslate.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
 * devenv: 776544c8ac0b10a37bd78f39ebf9f93a81a55de9
 * frontend: 9d112edc5bfe74a129a11d995abbe9c1600a338c
 * backend: 0e0ea11caf4b330b9c2ed7922540142bd9adc4af
  
### Step 2: 問題

  frontendが異常終了する

#### 再現のための手順:

  1. run `docker-compose up`
  
#### どうなってしまうか:

  * frontendがステータスコード1で終了する
  * ただし全体としては成功し、monitor_1は`ALL SERVICES are READY! Open http://localhost:8000/ in your browser.`を出力する。
  * ブラウザからlocalohst:8000にアクセスすると、`接続が拒否されました`と出ます

```
frontend_1  | Starting the development server...
frontend_1  |
frontend_1  | events.js:183
frontend_1  |       throw er; // Unhandled 'error' event
frontend_1  |       ^
frontend_1  |
frontend_1  | Error: listen EADDRINUSE 0.0.0.0:8000
frontend_1  |     at Object._errnoException (util.js:992:11)
frontend_1  |     at _exceptionWithHostPort (util.js:1014:20)
frontend_1  |     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
frontend_1  |     at listenInCluster (net.js:1396:12)
frontend_1  |     at doListen (net.js:1505:7)
frontend_1  |     at _combinedTickCallback (internal/process/next_tick.js:141:11)
frontend_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)
frontend_1  | error Command failed with exit code 1.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | error Command failed with signal "SIGTERM".
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | ERROR: "start:js" exited with 1.
frontend_1  | error Command failed with exit code 1.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | error Command failed with signal "SIGTERM".
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | error Command failed with signal "SIGTERM".
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
  
#### どうなるべきだったのか:

  * 異常終了せずに起動するはずだった
  
#### 関連するコード:

 --

**Comment by Cj-bc** [comment]
@coord-e からの指摘により、ほかにポート8000で動いてそうなコンテナを削除したところ、以下の警告以外は消え、正常に動きました。

```
frontend_1  | Something is already running on port 8000.
frontend_1  | (node:101) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard-react")
frontend_1  | (node:101) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "../node_modules/eslint-config-standard-jsx/index.js")
frontend_1  | (node:101) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

これは別件だと思うのでここは閉じます。
close 32
