### ISSUE TITLE
package.json自動インストールが落ちる

### ISSUE THREAD

**Issue by coord-e** [Sakuten/frontend#38]
### Step 1: 環境

 * OS: Linux coordiserver 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux
 * devenv: 6e69458cab00d5d41da508f57bb63a26d5b2295c
 * frontend: 9963db12db149d3b6b61a6174719f824a0b30dad
 * backend: 8f35d892d2da3b30e0fc0c0fbf570f7ad62765de
  
#### 再現のための手順:

  1. `./scripts/start.sh`
  2. `package.json`を編集する
  3. まつ
  
#### どうなってしまうか:

  * エラーを吐く

```
frontend_1  | [3/4] Linking dependencies...
frontend_1  | warning " > eslint-loader@1.9.0" has incorrect peer dependency "eslint@>=1.6.0 <5.0.0".
frontend_1  | warning " > eslint-plugin-jsx-a11y@5.1.1" has incorrect peer dependency "eslint@^2.10.2 || ^3 || ^4".
frontend_1  | warning " > mobx-react-router@4.0.4" has incorrect peer dependency "mobx@^3.0.0 || ^4.0.0".
frontend_1  | Compiling...
frontend_1  | Failed to compile.
frontend_1  |
frontend_1  | ./src/container/App.js
frontend_1  | Module not found: Can't resolve 'react-router-dom' in '/code/src/container'
frontend_1  | Compiling...
frontend_1  | /node_modules/react-dev-utils/ModuleScopePlugin.js:28
frontend_1  |         request.descriptionFileRoot.indexOf('/node_modules/') !== -1 ||
frontend_1  |                                     ^
frontend_1  |
frontend_1  | TypeError: Cannot read property 'indexOf' of undefined
frontend_1  |     at Resolver.resolver.plugin (/node_modules/react-dev-utils/ModuleScopePlugin.js:28:37)
frontend_1  |     at Resolver.applyPluginsAsyncSeriesBailResult1 (/node_modules/tapable/lib/Tapable.js:256:13)
frontend_1  |     at runNormal (/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
frontend_1  |     at Resolver.doResolve (/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
frontend_1  |     at Resolver.<anonymous> (/node_modules/enhanced-resolve/lib/TryNextPlugin.js:16:12)
frontend_1  |     at Resolver.applyPluginsAsyncSeriesBailResult1 (/node_modules/tapable/lib/Tapable.js:256:13)
frontend_1  |     at runNormal (/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
frontend_1  |     at Resolver.doResolve (/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
frontend_1  |     at Resolver.<anonymous> (/node_modules/enhanced-resolve/lib/FileKindPlugin.js:17:12)
frontend_1  |     at Resolver.applyPluginsAsyncSeriesBailResult1 (/node_modules/tapable/lib/Tapable.js:256:13)
frontend_1  |     at runNormal (/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
frontend_1  |     at Resolver.doResolve (/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
frontend_1  |     at Resolver.<anonymous> (/node_modules/enhanced-resolve/lib/NextPlugin.js:14:12)
frontend_1  |     at Resolver.applyPluginsAsyncSeriesBailResult1 (/node_modules/tapable/lib/Tapable.js:256:13)
frontend_1  |     at runAfter (/node_modules/enhanced-resolve/lib/Resolver.js:152:20)
frontend_1  |     at innerCallback (/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
frontend_1  | error Command failed with exit code 1.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | [4/4] Building fresh packages...
frontend_1  | error Command failed with signal "SIGTERM".
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
frontend_1  | ERROR: "start:js" exited with 1.
frontend_1  | error Command failed with exit code 1.
frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
devenv_frontend_1 exited with code 1
```

#### どうなるべきだったのか:

  * スムーズにインストールが入り、そして再コンパイルが入る
  
#### 関連:

 * https://github.com/facebook/create-react-app/issues/3676

**Comment by coord-e** [comment]
なぜかさっき落ちなかったです
